services:
  esl-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FS_HOST=host.docker.internal
      - ENDPOINT=wss://api.openai.com/v1/realtime?model=gpt-4o-realtime-preview-2024-10-01
      - NUMBER_TO_DIAL=99999
    depends_on:
      - freeswitch
  freeswitch:
    build:
      context: ./freeswitch
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      - EXTENSION_PASSWORD=extensionpassword
      - NUMBER_TO_DIAL=99999

